
version: '3.4'

services:
  appserver:
    image: appserver
    hostname: appserver
    build:
      context: .
      dockerfile: src/AppServer/Dockerfile
    ports:
      - 1234:1234
  splunk:
    image: splunk/splunk:latest
    hostname: splunk
    environment:
    - SPLUNK_START_ARGS=--accept-license
    - SPLUNK_PASSWORD=Password/1
    ports:
      - 8000:8000
  forwarder:
    image: forwarder
    hostname: forwarder
    build:
      context: .
      dockerfile: src/custom-splunkuniversalforwarder/Dockerfile
    environment:
    - SPLUNK_START_ARGS=--accept-license
    - SPLUNK_PASSWORD=Password/1
    ports:
      - 9997:9997



